spring:
  application:
    name: shop-back

  datasource:
    url: jdbc:mysql://localhost:3306/fashion_shop
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  logging:
    level:
      root: INFO
      com.inwoo.project.shopback: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.inwoo.project.shopback
  configuration:
    map-underscore-to-camel-case: true