spring:
  application:
    name: shop-back

  datasource:
    url: jdbc:mysql://localhost:3306/fashion_shop
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  logging:
    level:
      root: INFO
      com.inwoo.project.shopback: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080

mybatis:
  mapper-locations: classpath:api/mapper/*.xml
  type-aliases-package: com.inwoo.project.shopback.api.user
  configuration:
    map-underscore-to-camel-case: true

# JWT Configuration
jwt:
  secret: my-jwt-secret-key-for-shop-back-application-2024
  access-token-expire-time: 3600000    # 1시간 (1000 * 60 * 60)
  refresh-token-expire-time: 604800000  # 7일 (1000 * 60 * 60 * 24 * 7)