##################################################################
# 시프링시큐리티 : 인증/권한 미대상
##################################################################
security.permitAll:
  -

##################################################################
# 시프링시큐리티 : 권한 설정
##################################################################
security.roles: